#!/usr/bin/env python3
"""Backfill the Korean (`ko`) field into the already-generated per-clause
timeline metadata (data/*_clauses.json).

Context: data/*_clauses.json was generated by generate_all_clause_audio.py
*before* Korean translations existed in the lesson pages' STORY arrays, so
every clause object only has zh/py/en/jp. The clause-player.js focus card
now also wants a Korean line, so each clause needs a `ko` field split the
same way en/jp already are (by matching punctuation segments), and each
sentence needs a `sentKo` field alongside sentEn/sentJp.

This script does NOT regenerate any audio - clause audio is Chinese TTS
only (zh text), unaffected by adding a translation text field.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"

LESSONS = [
    {"html": "hanjia-jianwen.html", "slug": "hanjia"},
    {"html": "gugong.html", "slug": "gugong"},
    {"html": "yiheyuan.html", "slug": "yiheyuan"},
    {"html": "luotuo-he-yang.html", "slug": "luotuo"},
    {"html": "xiaoma-guohe.html", "slug": "xiaoma"},
    {"html": "houzi-lao-yueliang.html", "slug": "houzi"},
    {"html": "sima-guang.html", "slug": "sima"},
    {"html": "shu-xingxing.html", "slug": "xingxing"},
    {"html": "gushi-er-shou.html", "slug": "gushi"},
    {"html": "diqiu-qingjiegong.html", "slug": "diqiu"},
    {"html": "daziran-yuyan.html", "slug": "daziran"},
    {"html": "tanyue.html", "slug": "tanyue"},
]


def split_clauses_by_punct(text):
    if not text:
        return []
    puncts = set('，、；：。！？,!?;:')
    parts = []
    cur = ''
    chars = list(text)
    n = len(chars)
    i = 0
    while i < n:
        ch = chars[i]
        cur += ch
        if ch in puncts:
            if i + 1 < n and chars[i + 1] in '”’"\'':
                cur += chars[i + 1]
                i += 1
            parts.append(cur.strip())
            cur = ''
        i += 1
    if cur.strip():
        if parts:
            parts[-1] += cur.strip()
        else:
            parts.append(cur.strip())
    return [p for p in parts if p]


def extract_story_from_html(file_path):
    content = file_path.read_text(encoding='utf-8')
    m = re.search(r'const STORY = (\[[\s\S]*?\]);', content)
    if not m:
        raise RuntimeError(f"STORY array not found in {file_path}")
    raw_json = m.group(1)
    cleaned = re.sub(r'([{,]\s*)([a-zA-Z0-9_]+)\s*:', r'\1"\2":', raw_json)
    cleaned = re.sub(r',\s*([}\]])', r'\1', cleaned)
    return json.loads(cleaned)


def main():
    for l_info in LESSONS:
        html_file = ROOT / l_info['html']
        slug = l_info['slug']
        meta_file = DATA_DIR / f"{slug}_clauses.json"
        if not meta_file.exists():
            print(f"SKIP {slug}: {meta_file} not found")
            continue

        story_items = extract_story_from_html(html_file)
        ko_by_id = {item.get('id'): item.get('ko', '') for item in story_items}

        lesson_meta = json.loads(meta_file.read_text(encoding='utf-8'))
        missing_ko = [sid for sid in ko_by_id if not ko_by_id[sid]]
        if missing_ko:
            print(f"WARN {slug}: sentences without ko text in STORY: {missing_ko}")

        updated_clauses = 0
        for sent in lesson_meta['sentences']:
            sent_id = sent['sentId']
            full_ko = ko_by_id.get(sent_id, '')
            sent['sentKo'] = full_ko
            ko_clauses = split_clauses_by_punct(full_ko)

            for c_idx, c in enumerate(sent['clauses']):
                ko_c = ko_clauses[c_idx] if c_idx < len(ko_clauses) else full_ko
                c['ko'] = ko_c
                updated_clauses += 1

        meta_file.write_text(
            json.dumps(lesson_meta, ensure_ascii=False, indent=2),
            encoding='utf-8'
        )
        print(f"OK {slug}: {len(lesson_meta['sentences'])} sentences, {updated_clauses} clauses updated with ko")


if __name__ == '__main__':
    main()
